
breast_tumor_P2_prompts = [
    "A medical breast mammogram revealing an area of concern suggestive of a breast tumor.",
    "A mammogram displaying a mass in the breast that may indicate a tumor.",
    "A breast mammogram showing an abnormal mass potentially indicative of a tumor.",
    "A breast imaging study showing a concerning mass suggestive of a tumor.",
    "A medical mammogram identifying a distinct mass that could suggest a breast tumor.",
    "A breast mammogram with findings suggestive of a mass potentially indicating a tumor.",
    "A mammogram showing a prominent mass within the breast tissue suggestive of a tumor.",
    "A breast imaging scan revealing a mass that may be indicative of a tumor.",
    "A mammogram showing a significant area of density that could indicate a breast tumor.",
    "A medical breast scan revealing an unusual mass suggestive of a tumor.",
    "A breast mammogram detecting a mass that raises suspicion of a tumor.",
    "A breast imaging study showing a suspicious area that could represent a tumor.",
    "A medical mammogram highlighting a mass that may be indicative of a breast tumor.",
    "A breast imaging scan identifying a notable mass suggestive of a tumor.",
    "A mammogram showing an irregular mass in the breast that could indicate a tumor.",
    "A breast mammogram displaying a dense mass that may be suggestive of a tumor.",
    "A breast imaging study revealing an area of concern suggestive of a potential tumor.",
    "A medical mammogram detecting a suspicious mass that could indicate a breast tumor.",
    "A mammogram showing an area of increased density that may be indicative of a tumor.",
    "A breast scan revealing a concerning mass suggestive of a breast tumor."
]

lung_CT_P2_prompts = [
    "A medical CT scan displaying a clear and detailed image of the lung lobes, showcasing the separation between the upper and lower lobes.",
    "A medical CT scan capturing the intricate structure of the lung lobes, emphasizing the branching of the bronchial tree.",
    "A medical CT scan illustrating the well-defined boundaries between the upper, middle, and lower lobes of the lungs.",
    "A medical CT scan providing a comprehensive view of the lung lobes, highlighting the lobar bronchi and surrounding tissues.",
    "A medical CT scan showing a detailed cross-sectional view of the lung lobes, with a focus on the superior and inferior lobes.",
    "A medical CT scan presenting a clear visualization of the lung lobes, emphasizing the fissures that separate each lobe.",
    "A medical CT scan revealing the detailed anatomy of the lung lobes, with a focus on the bronchopulmonary segments.",
    "A medical CT scan capturing the fine structure of the lung lobes, showcasing the relationship between the lobes and the pleural cavities.",
    "A medical CT scan offering a sharp image of the lung lobes, highlighting the distribution of airways and blood vessels within each lobe.",
    "A medical CT scan displaying the distinct separation of the lung lobes, with clear visualization of the interlobar fissures.",
    "A medical CT scan illustrating the detailed anatomy of the lung lobes, focusing on the middle lobe of the right lung.",
    "A medical CT scan showing a precise image of the lung lobes, highlighting the upper lobe of the left lung and its connection to the main bronchus.",
    "A medical CT scan providing a comprehensive view of the lung lobes, with a focus on the right lung's upper, middle, and lower lobes.",
    "A medical CT scan presenting a clear and detailed image of the lung lobes, emphasizing the lower lobe's relationship with the diaphragm.",
    "A medical CT scan capturing the intricate structure of the lung lobes, highlighting the lobar bronchi and adjacent blood vessels.",
    "A medical CT scan displaying the fine details of the lung lobes, with a focus on the left lung's superior and inferior lobes.",
    "A medical CT scan showing the clear delineation of the lung lobes, with precise visualization of the right lung's middle lobe.",
    "A medical CT scan illustrating the detailed structure of the lung lobes, focusing on the separation between the lobes and the mediastinum.",
    "A medical CT scan offering a detailed image of the lung lobes, highlighting the upper and lower lobes' airways and vascular structures.",
    "A medical CT scan capturing the clear boundaries of the lung lobes, emphasizing the fissures and surrounding lung parenchyma."
]
benign_breast_tumor_P3_prompts = [
    "A medical breast mammogram showing a well-defined, round mass suggestive of a benign breast tumor.",
    "A medical breast mammogram showing a smooth, well-circumscribed mass suggestive of a benign breast tumor.",
    "A mammogram displaying a round, homogeneous mass indicative of a benign breast tumor.",
    "A breast imaging study revealing a well-defined, encapsulated mass likely representing a benign breast tumor.",
    "A mammogram showing a sharply marginated, round mass suggestive of a benign breast tumor.",
    "A breast scan identifying a well-defined, oval mass suggestive of a benign breast tumor.",
    "A medical breast mammogram displaying a lobulated, non-aggressive mass consistent with a benign tumor.",
    "A breast imaging scan showing a well-circumscribed, smooth mass indicative of a benign breast tumor.",
    "A mammogram revealing a low-density, well-delineated mass likely representing a benign breast tumor.",
    "A breast imaging study showing a well-margined, round mass suggestive of a benign breast tumor.",
    "A medical mammogram detecting a smooth, well-defined mass characteristic of a benign breast tumor.",
    "A mammogram displaying a non-invasive, well-defined mass suggestive of a benign breast tumor.",
    "A breast scan showing a well-contained, round mass likely indicating a benign breast tumor.",
    "A breast mammogram identifying a well-encapsulated, smooth mass consistent with a benign tumor.",
    "A medical mammogram revealing a well-defined, non-irregular mass suggestive of a benign breast tumor.",
    "A breast imaging study showing a homogenous, well-circumscribed mass indicative of a benign tumor.",
    "A mammogram displaying a non-spiculated, round mass suggestive of a benign breast tumor.",
    "A breast scan showing a smooth, encapsulated mass likely representing a benign breast tumor.",
    "A medical breast mammogram detecting a non-aggressive, well-defined mass characteristic of a benign tumor.",
    "A breast imaging study revealing a well-marginated, round mass indicative of a benign breast tumor.",
    "A mammogram displaying a smoothly contoured mass suggestive of a benign breast tumor."
]
malignant_breast_tumor_P3_prompts = [
    "A medical breast mammogram showing an irregularly shaped, spiculated mass suggestive of a malignant breast tumor.",
    "A medical breast mammogram showing an irregular, spiculated mass suggestive of a malignant breast tumor.",
    "A mammogram displaying a poorly defined, lobulated mass indicative of a malignant breast tumor.",
    "A breast imaging study revealing an irregularly shaped, invasive mass likely representing a malignant breast tumor.",
    "A mammogram showing a dense, spiculated mass suggestive of a malignant breast tumor.",
    "A breast scan identifying a poorly circumscribed, irregular mass suggestive of a malignant breast tumor.",
    "A medical breast mammogram displaying a heterogeneous, irregular mass consistent with a malignant tumor.",
    "A breast imaging scan showing a spiculated, invasive mass indicative of a malignant breast tumor.",
    "A mammogram revealing an ill-defined, irregular mass likely representing a malignant breast tumor.",
    "A breast imaging study showing an irregular, spiculated mass suggestive of a malignant breast tumor.",
    "A medical mammogram detecting a poorly defined, lobulated mass characteristic of a malignant breast tumor.",
    "A mammogram displaying an irregular, non-homogeneous mass suggestive of a malignant breast tumor.",
    "A breast scan showing a spiculated, invasive mass likely indicating a malignant breast tumor.",
    "A breast mammogram identifying an irregular, dense mass consistent with a malignant tumor.",
    "A medical mammogram revealing a spiculated, invasive mass suggestive of a malignant breast tumor.",
    "A breast imaging study showing a poorly marginated, irregular mass indicative of a malignant tumor.",
    "A mammogram displaying an irregularly shaped, spiculated mass suggestive of a malignant breast tumor.",
    "A breast scan showing an ill-defined, invasive mass likely representing a malignant breast tumor.",
    "A medical breast mammogram detecting a spiculated, irregular mass characteristic of a malignant tumor.",
    "A breast imaging study revealing a poorly circumscribed, irregular mass indicative of a malignant breast tumor.",
    "A mammogram displaying an irregular, invasive mass suggestive of a malignant breast tumor."
]
brain_tumor_P2_prompts = [
    "A medical brain MRI scan revealing a suspicious, irregularly shaped mass suggestive of a brain tumor.",
    "A brain MRI displaying an abnormal mass that could indicate the presence of a tumor.",
    "A brain imaging study showing an irregular mass potentially indicative of a brain tumor.",
    "A medical brain MRI scan identifying an unusual mass suggestive of a tumor in the brain.",
    "A brain MRI revealing a prominent mass within the brain tissue suggestive of a tumor.",
    "A brain imaging scan showing an irregularly shaped mass that may be indicative of a brain tumor.",
    "A brain MRI detecting a concerning mass suggestive of a tumor in the brain.",
    "A medical brain MRI scan showing a significant mass that could indicate a brain tumor.",
    "A brain imaging study identifying an abnormal, irregular mass suggestive of a brain tumor.",
    "A brain MRI displaying a notable mass within the brain potentially indicative of a tumor.",
    "A brain MRI revealing an irregular mass that could suggest a brain tumor.",
    "A brain imaging scan showing an abnormal mass that may be indicative of a brain tumor.",
    "A medical brain MRI scan identifying a distinct mass suggestive of a tumor in the brain.",
    "A brain MRI displaying an irregular mass that could be indicative of a brain tumor.",
    "A brain imaging study showing an unusual mass that may indicate a brain tumor.",
    "A brain MRI revealing an abnormal mass within the brain suggestive of a tumor.",
    "A medical brain MRI scan detecting a suspicious mass that could indicate a brain tumor.",
    "A brain imaging scan showing a prominent, irregular mass suggestive of a brain tumor.",
    "A brain MRI revealing an unusual mass potentially indicative of a brain tumor.",
    "A medical brain MRI scan identifying an abnormal, irregularly shaped mass suggestive of a brain tumor."
]
glioma_brain_tumor_P3_prompts = [
    "A medical brain MRI scan showing an infiltrative, irregularly shaped mass suggestive of a glioma tumor.",
    "A medical brain MRI scan showing an irregular, infiltrative mass suggestive of a glioma tumor.",
    "A brain MRI displaying a diffuse, poorly defined mass indicative of a glioma tumor.",
    "A brain imaging study revealing an irregularly shaped, invasive mass likely representing a glioma tumor.",
    "A brain MRI scan showing an infiltrative mass with irregular borders suggestive of a glioma tumor.",
    "A brain MRI revealing a heterogeneous, irregular mass potentially indicative of a glioma tumor.",
    "A brain imaging scan showing a poorly marginated, infiltrative mass suggestive of a glioma tumor.",
    "A brain MRI identifying an ill-defined, invasive mass indicative of a glioma tumor.",
    "A medical brain MRI scan detecting a diffuse, infiltrative mass suggestive of a glioma tumor.",
    "A brain imaging study showing an irregular, invasive mass potentially indicating a glioma tumor.",
    "A brain MRI displaying an infiltrative mass with indistinct margins suggestive of a glioma tumor.",
    "A brain MRI revealing a poorly circumscribed, irregular mass suggestive of a glioma tumor.",
    "A brain imaging scan showing an infiltrative mass with irregular borders indicative of a glioma tumor.",
    "A medical brain MRI scan identifying a diffuse, poorly defined mass suggestive of a glioma tumor.",
    "A brain MRI displaying a heterogeneous, infiltrative mass indicative of a glioma tumor.",
    "A brain imaging study showing an irregularly shaped, invasive mass suggestive of a glioma tumor.",
    "A brain MRI revealing an infiltrative mass with indistinct margins potentially indicative of a glioma tumor.",
    "A brain imaging scan showing a diffuse, irregular mass suggestive of a glioma tumor.",
    "A brain MRI identifying a poorly defined, infiltrative mass suggestive of a glioma tumor.",
    "A medical brain MRI scan detecting an irregular, invasive mass indicative of a glioma tumor.",
    "A brain imaging study revealing a diffuse, infiltrative mass suggestive of a glioma tumor."
]
meningioma_brain_tumor_P3_prompts = [
    "A medical brain MRI scan showing a well-circumscribed, extra-axial mass suggestive of a meningioma tumor.",
    "A brain MRI displaying a sharply marginated, extra-axial mass indicative of a meningioma tumor.",
    "A brain imaging study revealing a well-defined, dural-based mass likely representing a meningioma tumor.",
    "A brain MRI scan showing a round, extra-axial mass suggestive of a meningioma tumor.",
    "A brain MRI revealing a homogenous, well-circumscribed mass potentially indicative of a meningioma tumor.",
    "A brain imaging scan showing a well-marginated, dural-based mass suggestive of a meningioma tumor.",
    "A brain MRI identifying a smoothly contoured, extra-axial mass indicative of a meningioma tumor.",
    "A medical brain MRI scan detecting a well-defined, extra-axial mass suggestive of a meningioma tumor.",
    "A brain imaging study showing a sharply circumscribed, dural-based mass potentially indicating a meningioma tumor.",
    "A brain MRI displaying a well-circumscribed, round mass suggestive of a meningioma tumor.",
    "A brain MRI revealing a dural-based, homogenous mass suggestive of a meningioma tumor.",
    "A brain imaging scan showing a well-defined, smoothly contoured mass indicative of a meningioma tumor.",
    "A medical brain MRI scan identifying a round, extra-axial mass suggestive of a meningioma tumor.",
    "A brain MRI displaying a well-circumscribed, sharply marginated mass indicative of a meningioma tumor.",
    "A brain imaging study showing a homogenous, dural-based mass suggestive of a meningioma tumor.",
    "A brain MRI revealing a well-marginated, extra-axial mass potentially indicative of a meningioma tumor.",
    "A brain imaging scan showing a sharply defined, round mass suggestive of a meningioma tumor.",
    "A brain MRI identifying a dural-based, well-circumscribed mass suggestive of a meningioma tumor.",
    "A medical brain MRI scan detecting a homogenous, well-marginated mass indicative of a meningioma tumor.",
    "A brain imaging study revealing a well-defined, extra-axial mass suggestive of a meningioma tumor."
]
pituitary_brain_tumor_P3_prompts = [
    "A medical brain MRI scan showing a well-defined, sellar mass suggestive of a pituitary tumor.",
    "A brain MRI displaying a sharply circumscribed, sellar mass indicative of a pituitary tumor.",
    "A brain imaging study revealing a well-marginated, pituitary mass likely representing a pituitary tumor.",
    "A brain MRI scan showing a homogenous, sellar mass suggestive of a pituitary tumor.",
    "A brain MRI revealing a well-circumscribed, pituitary mass potentially indicative of a pituitary tumor.",
    "A brain imaging scan showing a smoothly contoured, sellar mass suggestive of a pituitary tumor.",
    "A brain MRI identifying a sharply marginated, sellar mass indicative of a pituitary tumor.",
    "A medical brain MRI scan detecting a well-defined, pituitary mass suggestive of a pituitary tumor.",
    "A brain imaging study showing a round, well-circumscribed sellar mass potentially indicating a pituitary tumor.",
    "A brain MRI displaying a homogenous, well-marginated sellar mass suggestive of a pituitary tumor.",
    "A brain MRI revealing a sharply defined, sellar mass suggestive of a pituitary tumor.",
    "A brain imaging scan showing a well-circumscribed, smoothly contoured sellar mass indicative of a pituitary tumor.",
    "A medical brain MRI scan identifying a homogenous, well-defined sellar mass suggestive of a pituitary tumor.",
    "A brain MRI displaying a well-marginated, sellar mass indicative of a pituitary tumor.",
    "A brain imaging study showing a sharply circumscribed, pituitary mass suggestive of a pituitary tumor.",
    "A brain MRI revealing a well-defined, homogenous sellar mass potentially indicative of a pituitary tumor.",
    "A brain imaging scan showing a well-marginated, sellar mass suggestive of a pituitary tumor.",
    "A brain MRI identifying a smoothly contoured, sellar mass suggestive of a pituitary tumor.",
    "A medical brain MRI scan detecting a sharply defined, pituitary mass indicative of a pituitary tumor.",
    "A brain imaging study revealing a well-circumscribed, sellar mass suggestive of a pituitary tumor."
]
lung_xray_P2_prompts = [
    "A medical chest X-ray showing findings suggestive of potential lung conditions.",
    "A chest X-ray displaying features consistent with the presence or absence of lung abnormalities.",
    "A chest imaging scan revealing findings that may indicate normal or abnormal lung conditions.",
    "A medical chest X-ray showing signs that could suggest lung health or disease.",
    "A chest X-ray displaying patterns consistent with various lung conditions.",
    "A chest imaging study revealing observations that may indicate the state of lung health.",
    "A medical chest X-ray showing features that could suggest the presence or absence of lung disease.",
    "A chest X-ray displaying findings that may indicate healthy or compromised lung function.",
    "A chest imaging scan revealing evidence that could suggest normal or abnormal lung status.",
    "A medical chest X-ray showing observations consistent with the potential presence or absence of lung issues.",
    "A chest X-ray displaying signs that could suggest a range of lung conditions.",
    "A chest imaging study revealing patterns that may indicate the state of the lungs.",
    "A medical chest X-ray showing evidence that may suggest lung abnormalities or normality.",
    "A chest X-ray displaying findings that could indicate the presence or absence of lung disease.",
    "A chest imaging scan revealing observations that may be consistent with healthy or diseased lungs.",
    "A medical chest X-ray showing features that may suggest normal lung function or potential issues.",
    "A chest X-ray displaying findings suggestive of various lung health conditions.",
    "A chest imaging study revealing evidence that could indicate the presence or absence of lung abnormalities.",
    "A medical chest X-ray showing patterns consistent with potential lung conditions.",
    "A chest X-ray displaying findings that may suggest the presence or absence of lung disease."
]
covid_lung_P3_prompts = [
    "A medical chest X-ray showing bilateral, hazy opacities suggestive of COVID-19 infection.",
    "A chest X-ray displaying diffuse, ground-glass opacities consistent with COVID-19.",
    "A medical chest X-ray revealing multifocal, bilateral opacities suggestive of COVID-19 infection.",
    "A chest X-ray showing peripheral ground-glass opacities indicative of COVID-19.",
    "A chest imaging study displaying diffuse, bilateral opacities consistent with COVID-19 infection.",
    "A medical chest X-ray showing bilateral, patchy opacities suggestive of COVID-19.",
    "A chest X-ray revealing diffuse, peripheral opacities indicative of COVID-19 infection.",
    "A chest imaging scan showing bilateral, hazy infiltrates consistent with COVID-19.",
    "A medical chest X-ray displaying widespread ground-glass opacities suggestive of COVID-19.",
    "A chest X-ray revealing bilateral, diffuse opacities indicative of COVID-19 infection.",
    "A medical chest X-ray showing patchy, bilateral opacities consistent with COVID-19.",
    "A chest X-ray displaying ground-glass opacities in both lungs suggestive of COVID-19.",
    "A chest imaging study showing diffuse, bilateral infiltrates indicative of COVID-19 infection.",
    "A medical chest X-ray revealing hazy, peripheral opacities consistent with COVID-19.",
    "A chest X-ray displaying multifocal, bilateral opacities suggestive of COVID-19.",
    "A chest imaging scan showing bilateral, diffuse ground-glass opacities consistent with COVID-19 infection.",
    "A medical chest X-ray revealing bilateral, patchy opacities indicative of COVID-19.",
    "A chest X-ray displaying diffuse, peripheral ground-glass opacities suggestive of COVID-19.",
    "A medical chest X-ray showing bilateral, widespread opacities consistent with COVID-19 infection.",
    "A chest X-ray revealing diffuse, hazy opacities in both lungs suggestive of COVID-19."
]
viral_pneumonia_lung_P3_prompts = [
    "A medical chest X-ray showing diffuse, patchy infiltrates suggestive of viral pneumonia.",
    "A chest X-ray displaying bilateral, interstitial infiltrates indicative of viral pneumonia.",
    "A medical chest X-ray revealing widespread, patchy opacities consistent with viral pneumonia.",
    "A chest X-ray showing bilateral, diffuse infiltrates suggestive of viral pneumonia.",
    "A chest imaging study displaying patchy, bilateral opacities indicative of viral pneumonia.",
    "A medical chest X-ray showing diffuse, multifocal infiltrates suggestive of viral pneumonia.",
    "A chest X-ray revealing bilateral, diffuse opacities consistent with viral pneumonia.",
    "A chest imaging scan showing patchy, interstitial infiltrates suggestive of viral pneumonia.",
    "A medical chest X-ray displaying diffuse, bilateral opacities indicative of viral pneumonia.",
    "A chest X-ray revealing widespread, patchy infiltrates consistent with viral pneumonia.",
    "A medical chest X-ray showing bilateral, diffuse infiltrates indicative of viral pneumonia.",
    "A chest X-ray displaying patchy, multifocal opacities suggestive of viral pneumonia.",
    "A chest imaging study showing bilateral, interstitial opacities consistent with viral pneumonia.",
    "A medical chest X-ray revealing diffuse, patchy infiltrates indicative of viral pneumonia.",
    "A chest X-ray displaying bilateral, diffuse opacities suggestive of viral pneumonia.",
    "A chest imaging scan showing widespread, patchy infiltrates consistent with viral pneumonia.",
    "A medical chest X-ray revealing patchy, interstitial infiltrates suggestive of viral pneumonia.",
    "A chest X-ray displaying diffuse, bilateral infiltrates indicative of viral pneumonia.",
    "A medical chest X-ray showing multifocal, patchy opacities suggestive of viral pneumonia.",
    "A chest X-ray revealing widespread, bilateral infiltrates consistent with viral pneumonia."
]
lung_opacity_P3_prompts = [
    "A medical chest X-ray showing a localized, dense opacity suggestive of a lung lesion.",
    "A chest X-ray displaying a well-defined opacity consistent with a lung abnormality.",
    "A medical chest X-ray revealing a solitary, dense opacity indicative of a lung lesion.",
    "A chest X-ray showing a focal, dense opacity suggestive of a pulmonary lesion.",
    "A chest imaging study displaying a localized, well-circumscribed opacity consistent with a lung lesion.",
    "A medical chest X-ray showing a solitary opacity suggestive of a lung abnormality.",
    "A chest X-ray revealing a dense, localized opacity indicative of a pulmonary lesion.",
    "A chest imaging scan showing a well-defined opacity suggestive of a lung lesion.",
    "A medical chest X-ray displaying a focal, solitary opacity consistent with a lung lesion.",
    "A chest X-ray revealing a dense, well-circumscribed opacity suggestive of a lung lesion.",
    "A medical chest X-ray showing a localized opacity indicative of a lung abnormality.",
    "A chest X-ray displaying a solitary, dense opacity suggestive of a lung lesion.",
    "A chest imaging study showing a well-circumscribed opacity consistent with a lung lesion.",
    "A medical chest X-ray revealing a focal opacity suggestive of a pulmonary lesion.",
    "A chest X-ray displaying a dense, localized opacity indicative of a lung lesion.",
    "A chest imaging scan showing a solitary, well-defined opacity suggestive of a lung lesion.",
    "A medical chest X-ray revealing a dense, solitary opacity consistent with a lung lesion.",
    "A chest X-ray displaying a localized, well-defined opacity suggestive of a lung lesion.",
    "A medical chest X-ray showing a well-circumscribed opacity indicative of a lung lesion.",
    "A chest X-ray revealing a solitary, dense opacity suggestive of a pulmonary lesion."
]
normal_lung_P3_prompts = [
    "A medical chest X-ray showing clear lung fields with no visible abnormalities, indicating a normal scan.",
    "A chest X-ray displaying normal lung structures with no signs of disease.",
    "A medical chest X-ray revealing clear, unremarkable lung fields consistent with a normal scan.",
    "A chest X-ray showing no abnormalities in the lung fields, suggestive of a healthy scan.",
    "A chest imaging study displaying clear, normal lung fields with no evidence of disease.",
    "A medical chest X-ray showing well-aerated lungs with no visible abnormalities, indicating a normal scan.",
    "A chest X-ray revealing normal lung fields with no signs of pathology.",
    "A chest imaging scan showing clear lung fields with no evidence of disease, suggesting a normal scan.",
    "A medical chest X-ray displaying normal, unremarkable lung structures consistent with a healthy scan.",
    "A chest X-ray showing no signs of abnormalities in the lung fields, indicating a normal scan.",
    "A medical chest X-ray revealing clear lung fields with no evidence of disease, suggestive of a normal scan.",
    "A chest X-ray displaying normal lung structures with no visible signs of disease.",
    "A chest imaging study showing clear, well-aerated lung fields with no abnormalities, indicating a normal scan.",
    "A medical chest X-ray revealing normal lung fields with no visible signs of pathology.",
    "A chest X-ray displaying clear lung fields with no evidence of abnormalities, suggestive of a normal scan.",
    "A chest imaging scan showing no signs of disease in the lung fields, indicating a normal scan.",
    "A medical chest X-ray displaying well-aerated lungs with no signs of abnormalities, suggesting a normal scan.",
    "A chest X-ray revealing clear, normal lung fields with no visible signs of disease.",
    "A chest imaging study showing no evidence of abnormalities in the lung fields, indicating a normal scan.",
    "A medical chest X-ray revealing normal lung structures with no signs of disease, consistent with a healthy scan."
]